import type { AwardCategory } from '@/types/home'

export const AWARDS: readonly AwardCategory[] = [
  {
    id: 'top-talent',
    titleKey: 'home.awards.top-talent.title',
    descriptionKey: 'home.awards.top-talent.description',
    descriptionLongKey: 'awards.top-talent.descriptionLong',
    image: '/assets/home/awards/top-talent.png',
    nameOverlayImage: '/assets/awards/overlays/top-talent.png',
    slug: 'top-talent',
    quantity: 10,
    quantityUnit: 'unit',
    values: [{ amountVnd: 7_000_000, captionKey: 'awards.label.perAward' }],
  },
  {
    id: 'top-project',
    titleKey: 'home.awards.top-project.title',
    descriptionKey: 'home.awards.top-project.description',
    descriptionLongKey: 'awards.top-project.descriptionLong',
    image: '/assets/home/awards/top-project.png',
    nameOverlayImage: '/assets/awards/overlays/top-project.png',
    slug: 'top-project',
    quantity: 2,
    quantityUnit: 'team',
    values: [{ amountVnd: 15_000_000, captionKey: 'awards.label.perAward' }],
  },
  {
    id: 'top-project-leader',
    titleKey: 'home.awards.top-project-leader.title',
    descriptionKey: 'home.awards.top-project-leader.description',
    descriptionLongKey: 'awards.top-project-leader.descriptionLong',
    image: '/assets/home/awards/top-project-leader.png',
    nameOverlayImage: '/assets/awards/overlays/top-project-leader.png',
    slug: 'top-project-leader',
    quantity: 3,
    quantityUnit: 'individual',
    values: [{ amountVnd: 7_000_000 }],
  },
  {
    id: 'best-manager',
    titleKey: 'home.awards.best-manager.title',
    descriptionKey: 'home.awards.best-manager.description',
    descriptionLongKey: 'awards.best-manager.descriptionLong',
    image: '/assets/home/awards/best-manager.png',
    nameOverlayImage: '/assets/awards/overlays/best-manager.png',
    slug: 'best-manager',
    quantity: 1,
    quantityUnit: 'individual',
    values: [{ amountVnd: 10_000_000 }],
  },
  {
    id: 'signature-2025-creator',
    titleKey: 'home.awards.signature-2025-creator.title',
    descriptionKey: 'home.awards.signature-2025-creator.description',
    descriptionLongKey: 'awards.signature-2025-creator.descriptionLong',
    image: '/assets/home/awards/signature-2025-creator.png',
    nameOverlayImage: '/assets/awards/overlays/signature-2025-creator.png',
    slug: 'signature-2025-creator',
    quantity: 1,
    quantityUnit: 'unit',
    values: [
      { amountVnd: 5_000_000, recipientType: 'individual' },
      { amountVnd: 8_000_000, recipientType: 'team' },
    ],
  },
  {
    id: 'mvp',
    titleKey: 'home.awards.mvp.title',
    descriptionKey: 'home.awards.mvp.description',
    descriptionLongKey: 'awards.mvp.descriptionLong',
    image: '/assets/home/awards/mvp.png',
    nameOverlayImage: '/assets/awards/overlays/mvp.png',
    slug: 'mvp',
    quantity: 1,
    quantityUnit: 'unit',
    values: [{ amountVnd: 15_000_000 }],
  },
] as const
